kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    deployment.kubernetes.io/revision: '1'
  name: client-jwks-server
  namespace: fapi
  labels:
    app: client-jwks-server
    app.kubernetes.io/component: client-jwks-server
    app.kubernetes.io/instance: client-jwks-server
    app.kubernetes.io/name: client-jwks-server
    app.kubernetes.io/part-of: client-jwks-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-jwks-server
  template:
    metadata:
      labels:
        app: client-jwks-server
        deploymentconfig: client-jwks-server
    spec:
      containers:
        - name: client-jwks-server
          args:
            - /keys
          image: >-
            image-registry.openshift-image-registry.svc:5000/openshift/obbr-kc-sig-fapi_client_jwks_server
          ports:
            - containerPort: 3000
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
