apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  namespace: fapi
  name: keycloak
  labels:
    app: sso
spec:
  profile: preview
  externalAccess:
    enabled: true
    tlsTermination: passthrough
  keycloakDeploymentSpec:
    experimental:
      env:
        - name: KEYCLOAK_LOGLEVEL
          value: ALL
        - name: X509_CA_BUNDLE
          value: >-
            /etc/x509/client/client-ca.crt
            /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      volumes:
        defaultMode: 0777
        items:
          - configMap:
              mountPath: /etc/x509/client
              name: fapi-client-ca-config
              items:
                - key: client-ca.crt
                  mode: 0777
                  path: client-ca.crt
  extensions:
    - >-
      https://github.com/aerogear/keycloak-metrics-spi/releases/download/1.0.4/keycloak-metrics-spi-1.0.4.jar
  instances: 1
